name: Build and Push Custom Caddy Container

on:
  workflow_dispatch: # Allows manual runs

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Caddy Release
        id: fetch_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest)
          echo "$latest_release" > release.json
          tag_name=$(jq -r '.tag_name' release.json)
          echo "latest_tag=$tag_name" >> $GITHUB_ENV

      - name: Check Current Container Tag
        id: check_current_tag
        run: |
          if ghcr_image=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://ghcr.io/v2/callumau/caddy-cloudflare/caddy/manifests/latest | jq -r '.annotations."org.opencontainers.image.version"'); then
            echo "current_tag=$ghcr_image" >> $GITHUB_ENV
          else
            echo "current_tag=none" >> $GITHUB_ENV
          fi

      - name: Compare Tags and Build New Image
        if: env.latest_tag != env.current_tag
        run: |
          echo "New release detected: ${{ env.latest_tag }}"
          docker build \
            --build-arg CADDY_VERSION=${{ env.latest_tag }} \
            -t ghcr.io/callumau/caddy-cloudflare/caddy:${{ env.latest_tag }} \
            -t ghcr.io/callumau/caddy-cloudflare/caddy:latest .

      - name: Push New Image to GHCR
        if: env.latest_tag != env.current_tag
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/callumau/caddy-cloudflare/caddy:${{ env.latest_tag }}
          docker push ghcr.io/callumau/caddy-cloudflare/caddy:latest

      - name: No New Release Detected
        if: env.latest_tag == env.current_tag
        run: echo "No new release detected. Skipping build and push."
