name: Poll for New Releases

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes. Adjust as needed.

jobs:
  poll-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository Details
        id: setup
        run: |
          echo "owner=caddyserver" >> $GITHUB_ENV
          echo "repo=caddy" >> $GITHUB_ENV
          echo "last_tag_file=.last_release_tag" >> $GITHUB_ENV

      - name: Get Latest Release
        id: get_release
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ env.owner }}/${{ env.repo }}/releases/latest")

          echo "$response" > release.json
          tag_name=$(jq -r '.tag_name' release.json)

          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "release_name=$(jq -r '.name' release.json)" >> $GITHUB_ENV
          echo "release_body=$(jq -r '.body' release.json)" >> $GITHUB_ENV

      - name: Check for New Release
        id: check_release
        run: |
          if [ ! -f "${{ env.last_tag_file }}" ]; then
            echo "No previous release found. Saving current tag."
            echo "${{ env.tag_name }}" > ${{ env.last_tag_file }}
            echo "new_release=false" >> $GITHUB_ENV
          else
            last_tag=$(cat ${{ env.last_tag_file }})
            if [ "$last_tag" != "${{ env.tag_name }}" ]; then
              echo "New release found: ${{ env.tag_name }}"
              echo "${{ env.tag_name }}" > ${{ env.last_tag_file }}
              echo "new_release=true" >> $GITHUB_ENV
            else
              echo "No new release."
              echo "new_release=false" >> $GITHUB_ENV
            fi
          fi

      - name: Handle New Release
        if: steps.check_release.outputs.new_release == 'true'
        run: |
          echo "New release detected!"
          echo "Release Tag: ${{ env.tag_name }}"
          echo "Release Name: ${{ env.release_name }}"
          echo "Release Body: ${{ env.release_body }}"

      # Add any additional steps to handle the new release
